-- 请在 Supabase 控制台的 SQL Editor 中粘贴并运行以下代码

-- 1. 创建信件表
CREATE TABLE letters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  target_time TIMESTAMP WITH TIME ZONE NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. 开启行级安全策略 (RLS)
ALTER TABLE letters ENABLE ROW LEVEL SECURITY;

-- 3. 允许匿名读写策略（针对当前个人工具项目最简配置）
-- 警告：如果这是一个面向大众的商业产品，需要加入 user_id 鉴权！
CREATE POLICY "Allow anonymous select" ON letters FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert" ON letters FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous update" ON letters FOR UPDATE USING (true);
