-- 请在 Supabase 控制台的 SQL Editor 中粘贴并运行以下代码
-- 支持首次初始化，也支持对现有库做增量迁移

-- 1) 信件主表
CREATE TABLE IF NOT EXISTS letters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  target_time TIMESTAMP WITH TIME ZONE NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 增强字段：失败重试次数、最近错误、送达时间
ALTER TABLE letters ADD COLUMN IF NOT EXISTS retry_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE letters ADD COLUMN IF NOT EXISTS last_error TEXT;
ALTER TABLE letters ADD COLUMN IF NOT EXISTS sent_at TIMESTAMP WITH TIME ZONE;

-- 2) 投递日志表
CREATE TABLE IF NOT EXISTS delivery_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  letter_id BIGINT NOT NULL REFERENCES letters(id) ON DELETE CASCADE,
  attempt_no INTEGER NOT NULL,
  result TEXT NOT NULL CHECK (result IN ('success', 'failed')),
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_letters_status_target_time ON letters(status, target_time);
CREATE INDEX IF NOT EXISTS idx_delivery_logs_letter_id ON delivery_logs(letter_id);
CREATE INDEX IF NOT EXISTS idx_delivery_logs_created_at ON delivery_logs(created_at DESC);

-- 3) 开启 RLS
ALTER TABLE letters ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_logs ENABLE ROW LEVEL SECURITY;

-- 4) 最简策略（个人工具使用；若对外开放请改为按用户鉴权）
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'letters' AND policyname = 'Allow anonymous select'
  ) THEN
    CREATE POLICY "Allow anonymous select" ON letters FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'letters' AND policyname = 'Allow anonymous insert'
  ) THEN
    CREATE POLICY "Allow anonymous insert" ON letters FOR INSERT WITH CHECK (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'letters' AND policyname = 'Allow anonymous update'
  ) THEN
    CREATE POLICY "Allow anonymous update" ON letters FOR UPDATE USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'delivery_logs' AND policyname = 'Allow anonymous select logs'
  ) THEN
    CREATE POLICY "Allow anonymous select logs" ON delivery_logs FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'delivery_logs' AND policyname = 'Allow anonymous insert logs'
  ) THEN
    CREATE POLICY "Allow anonymous insert logs" ON delivery_logs FOR INSERT WITH CHECK (true);
  END IF;
END $$;
